# Generated by Django 5.0.7 on 2024-09-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='data',
            field=models.CharField(max_length=64, verbose_name='chat'),
        ),
    ]
