# Generated by Django 5.0.7 on 2024-09-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chats_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='to_user',
        ),
        migrations.AddField(
            model_name='chats',
            name='to_user',
            field=models.CharField(default='user', max_length=24, verbose_name='user'),
        ),
    ]
