# Generated by Django 5.0.7 on 2024-09-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
