# Generated by Django 5.0.7 on 2024-09-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='user1', max_length=64, verbose_name='username')),
                ('edit_able', models.BooleanField(default=False)),
            ],
        ),
    ]
