# Generated by Django 5.0.7 on 2024-09-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='user1', max_length=64, verbose_name='username')),
                ('title', models.CharField(default='Book', max_length=64, verbose_name='Title')),
                ('link', models.CharField(default='/chat/index.html', max_length=1024, verbose_name='Book link')),
                ('image', models.CharField(default='https://static.vecteezy.com/system/resources/previews/009/399/398/non_2x/old-vintage-book-clipart-design-illustration-free-png.png', max_length=1024, verbose_name='Book image link')),
                ('author', models.CharField(max_length=1024, verbose_name='Book link')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Last Update')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
