# Generated by Django 5.0.7 on 2024-09-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_books_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='user1', max_length=64, verbose_name='username')),
                ('name', models.CharField(default='assignment', max_length=256, verbose_name='assignment')),
                ('prof', models.CharField(default='user1', max_length=64, verbose_name='username')),
                ('time', models.DateField(verbose_name='deadline')),
            ],
        ),
    ]
