# Generated by Django 5.0.7 on 2024-09-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='user1', max_length=64, verbose_name='username')),
                ('subject_name', models.CharField(default='biotech', max_length=256, verbose_name='subject_name')),
                ('student', models.CharField(default='user1', max_length=64, verbose_name='name')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='updated on:')),
                ('description', models.TextField(verbose_name='description')),
                ('link', models.URLField(verbose_name='url for the notes')),
            ],
        ),
    ]
